System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system",
      "es7.decorators"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build.js": [
      "app.js",
      "npm:react-dom@15.3.1.js",
      "npm:react-dom@15.3.1/index.js",
      "npm:react@15.3.1/lib/ReactDOM.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.9.js",
      "npm:process@0.11.9/browser.js",
      "npm:react@15.3.1/lib/ReactDOMNullInputValuePropHook.js",
      "npm:fbjs@0.8.4/lib/warning.js",
      "npm:fbjs@0.8.4/lib/emptyFunction.js",
      "npm:react@15.3.1/lib/ReactComponentTreeHook.js",
      "npm:fbjs@0.8.4/lib/invariant.js",
      "npm:react@15.3.1/lib/ReactCurrentOwner.js",
      "npm:react@15.3.1/lib/reactProdInvariant.js",
      "npm:react@15.3.1/lib/ReactDOMUnknownPropertyHook.js",
      "npm:react@15.3.1/lib/EventPluginRegistry.js",
      "npm:react@15.3.1/lib/DOMProperty.js",
      "npm:react@15.3.1/lib/ReactInstrumentation.js",
      "npm:react@15.3.1/lib/ReactDebugTool.js",
      "npm:fbjs@0.8.4/lib/performanceNow.js",
      "npm:fbjs@0.8.4/lib/performance.js",
      "npm:fbjs@0.8.4/lib/ExecutionEnvironment.js",
      "npm:react@15.3.1/lib/ReactChildrenMutationWarningHook.js",
      "npm:react@15.3.1/lib/ReactHostOperationHistoryHook.js",
      "npm:react@15.3.1/lib/ReactInvalidSetStateWarningHook.js",
      "npm:react@15.3.1/lib/renderSubtreeIntoContainer.js",
      "npm:react@15.3.1/lib/ReactMount.js",
      "npm:react@15.3.1/lib/shouldUpdateReactComponent.js",
      "npm:react@15.3.1/lib/setInnerHTML.js",
      "npm:react@15.3.1/lib/createMicrosoftUnsafeLocalFunction.js",
      "npm:react@15.3.1/lib/DOMNamespaces.js",
      "npm:react@15.3.1/lib/instantiateReactComponent.js",
      "npm:react@15.3.1/lib/ReactHostComponent.js",
      "npm:object-assign@4.1.0.js",
      "npm:object-assign@4.1.0/index.js",
      "npm:react@15.3.1/lib/ReactEmptyComponent.js",
      "npm:react@15.3.1/lib/ReactCompositeComponent.js",
      "npm:fbjs@0.8.4/lib/shallowEqual.js",
      "npm:fbjs@0.8.4/lib/emptyObject.js",
      "npm:react@15.3.1/lib/checkReactTypeSpec.js",
      "npm:react@15.3.1/lib/ReactPropTypesSecret.js",
      "npm:react@15.3.1/lib/ReactPropTypeLocationNames.js",
      "npm:react@15.3.1/lib/ReactReconciler.js",
      "npm:react@15.3.1/lib/ReactRef.js",
      "npm:react@15.3.1/lib/ReactOwner.js",
      "npm:react@15.3.1/lib/ReactPropTypeLocations.js",
      "npm:fbjs@0.8.4/lib/keyMirror.js",
      "npm:react@15.3.1/lib/ReactNodeTypes.js",
      "npm:react@15.3.1/lib/ReactElement.js",
      "npm:react@15.3.1/lib/canDefineProperty.js",
      "npm:react@15.3.1/lib/ReactInstanceMap.js",
      "npm:react@15.3.1/lib/ReactErrorUtils.js",
      "npm:react@15.3.1/lib/ReactComponentEnvironment.js",
      "npm:react@15.3.1/lib/ReactUpdates.js",
      "npm:react@15.3.1/lib/Transaction.js",
      "npm:react@15.3.1/lib/ReactFeatureFlags.js",
      "npm:react@15.3.1/lib/PooledClass.js",
      "npm:react@15.3.1/lib/CallbackQueue.js",
      "npm:react@15.3.1/lib/ReactUpdateQueue.js",
      "npm:react@15.3.1/lib/ReactMarkupChecksum.js",
      "npm:react@15.3.1/lib/adler32.js",
      "npm:react@15.3.1/lib/ReactDOMFeatureFlags.js",
      "npm:react@15.3.1/lib/ReactDOMContainerInfo.js",
      "npm:react@15.3.1/lib/validateDOMNesting.js",
      "npm:react@15.3.1/lib/ReactDOMComponentTree.js",
      "npm:react@15.3.1/lib/ReactDOMComponentFlags.js",
      "npm:react@15.3.1/lib/ReactBrowserEventEmitter.js",
      "npm:react@15.3.1/lib/isEventSupported.js",
      "npm:react@15.3.1/lib/getVendorPrefixedEventName.js",
      "npm:react@15.3.1/lib/ViewportMetrics.js",
      "npm:react@15.3.1/lib/ReactEventEmitterMixin.js",
      "npm:react@15.3.1/lib/EventPluginHub.js",
      "npm:react@15.3.1/lib/forEachAccumulated.js",
      "npm:react@15.3.1/lib/accumulateInto.js",
      "npm:react@15.3.1/lib/EventPluginUtils.js",
      "npm:react@15.3.1/lib/EventConstants.js",
      "npm:react@15.3.1/lib/DOMLazyTree.js",
      "npm:react@15.3.1/lib/setTextContent.js",
      "npm:react@15.3.1/lib/escapeTextContentForBrowser.js",
      "npm:react@15.3.1/lib/getHostComponentFromComposite.js",
      "npm:react@15.3.1/lib/findDOMNode.js",
      "npm:react@15.3.1/lib/ReactVersion.js",
      "npm:react@15.3.1/lib/ReactDefaultInjection.js",
      "npm:react@15.3.1/lib/SimpleEventPlugin.js",
      "npm:fbjs@0.8.4/lib/keyOf.js",
      "npm:react@15.3.1/lib/getEventCharCode.js",
      "npm:react@15.3.1/lib/SyntheticWheelEvent.js",
      "npm:react@15.3.1/lib/SyntheticMouseEvent.js",
      "npm:react@15.3.1/lib/getEventModifierState.js",
      "npm:react@15.3.1/lib/SyntheticUIEvent.js",
      "npm:react@15.3.1/lib/getEventTarget.js",
      "npm:react@15.3.1/lib/SyntheticEvent.js",
      "npm:react@15.3.1/lib/SyntheticTransitionEvent.js",
      "npm:react@15.3.1/lib/SyntheticTouchEvent.js",
      "npm:react@15.3.1/lib/SyntheticDragEvent.js",
      "npm:react@15.3.1/lib/SyntheticKeyboardEvent.js",
      "npm:react@15.3.1/lib/getEventKey.js",
      "npm:react@15.3.1/lib/SyntheticFocusEvent.js",
      "npm:react@15.3.1/lib/SyntheticClipboardEvent.js",
      "npm:react@15.3.1/lib/SyntheticAnimationEvent.js",
      "npm:react@15.3.1/lib/EventPropagators.js",
      "npm:fbjs@0.8.4/lib/EventListener.js",
      "npm:react@15.3.1/lib/SelectEventPlugin.js",
      "npm:react@15.3.1/lib/isTextInputElement.js",
      "npm:fbjs@0.8.4/lib/getActiveElement.js",
      "npm:react@15.3.1/lib/ReactInputSelection.js",
      "npm:fbjs@0.8.4/lib/focusNode.js",
      "npm:fbjs@0.8.4/lib/containsNode.js",
      "npm:fbjs@0.8.4/lib/isTextNode.js",
      "npm:fbjs@0.8.4/lib/isNode.js",
      "npm:react@15.3.1/lib/ReactDOMSelection.js",
      "npm:react@15.3.1/lib/getTextContentAccessor.js",
      "npm:react@15.3.1/lib/getNodeForCharacterOffset.js",
      "npm:react@15.3.1/lib/SVGDOMPropertyConfig.js",
      "npm:react@15.3.1/lib/ReactReconcileTransaction.js",
      "npm:react@15.3.1/lib/ReactInjection.js",
      "npm:react@15.3.1/lib/ReactClass.js",
      "npm:react@15.3.1/lib/ReactNoopUpdateQueue.js",
      "npm:react@15.3.1/lib/ReactComponent.js",
      "npm:react@15.3.1/lib/ReactEventListener.js",
      "npm:fbjs@0.8.4/lib/getUnboundedScrollPosition.js",
      "npm:react@15.3.1/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@15.3.1/lib/ReactDOMTextComponent.js",
      "npm:react@15.3.1/lib/DOMChildrenOperations.js",
      "npm:react@15.3.1/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@15.3.1/lib/Danger.js",
      "npm:fbjs@0.8.4/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.8.4/lib/getMarkupWrap.js",
      "npm:fbjs@0.8.4/lib/createArrayFromMixed.js",
      "npm:react@15.3.1/lib/ReactDOMTreeTraversal.js",
      "npm:react@15.3.1/lib/ReactDOMEmptyComponent.js",
      "npm:react@15.3.1/lib/ReactDOMComponent.js",
      "npm:react@15.3.1/lib/ReactServerRenderingTransaction.js",
      "npm:react@15.3.1/lib/ReactServerUpdateQueue.js",
      "npm:react@15.3.1/lib/ReactMultiChild.js",
      "npm:react@15.3.1/lib/flattenChildren.js",
      "npm:react@15.3.1/lib/traverseAllChildren.js",
      "npm:react@15.3.1/lib/KeyEscapeUtils.js",
      "npm:react@15.3.1/lib/getIteratorFn.js",
      "npm:react@15.3.1/lib/ReactChildReconciler.js",
      "npm:react@15.3.1/lib/ReactDOMTextarea.js",
      "npm:react@15.3.1/lib/LinkedValueUtils.js",
      "npm:react@15.3.1/lib/ReactPropTypes.js",
      "npm:react@15.3.1/lib/DisabledInputUtils.js",
      "npm:react@15.3.1/lib/ReactDOMSelect.js",
      "npm:react@15.3.1/lib/ReactDOMOption.js",
      "npm:react@15.3.1/lib/ReactChildren.js",
      "npm:react@15.3.1/lib/ReactDOMInput.js",
      "npm:react@15.3.1/lib/DOMPropertyOperations.js",
      "npm:react@15.3.1/lib/quoteAttributeValueForBrowser.js",
      "npm:react@15.3.1/lib/ReactDOMButton.js",
      "npm:react@15.3.1/lib/CSSPropertyOperations.js",
      "npm:fbjs@0.8.4/lib/memoizeStringOnly.js",
      "npm:fbjs@0.8.4/lib/hyphenateStyleName.js",
      "npm:fbjs@0.8.4/lib/hyphenate.js",
      "npm:react@15.3.1/lib/dangerousStyleValue.js",
      "npm:react@15.3.1/lib/CSSProperty.js",
      "npm:fbjs@0.8.4/lib/camelizeStyleName.js",
      "npm:fbjs@0.8.4/lib/camelize.js",
      "npm:react@15.3.1/lib/AutoFocusUtils.js",
      "npm:react@15.3.1/lib/ReactComponentBrowserEnvironment.js",
      "npm:react@15.3.1/lib/ReactDOMIDOperations.js",
      "npm:react@15.3.1/lib/HTMLDOMPropertyConfig.js",
      "npm:react@15.3.1/lib/EnterLeaveEventPlugin.js",
      "npm:react@15.3.1/lib/DefaultEventPluginOrder.js",
      "npm:react@15.3.1/lib/ChangeEventPlugin.js",
      "npm:react@15.3.1/lib/BeforeInputEventPlugin.js",
      "npm:react@15.3.1/lib/SyntheticInputEvent.js",
      "npm:react@15.3.1/lib/SyntheticCompositionEvent.js",
      "npm:react@15.3.1/lib/FallbackCompositionState.js",
      "components/Layout.js",
      "npm:material-ui@0.15.4/styles.js",
      "npm:material-ui@0.15.4/styles/index.js",
      "npm:material-ui@0.15.4/styles/zIndex.js",
      "npm:material-ui@0.15.4/styles/typography.js",
      "npm:material-ui@0.15.4/styles/colors.js",
      "npm:material-ui@0.15.4/styles/transitions.js",
      "npm:material-ui@0.15.4/styles/themeManager.js",
      "npm:warning@3.0.0.js",
      "npm:warning@3.0.0/browser.js",
      "npm:material-ui@0.15.4/styles/getMuiTheme.js",
      "npm:recompose@0.20.2/compose.js",
      "npm:material-ui@0.15.4/utils/rtl.js",
      "npm:material-ui@0.15.4/utils/callOnce.js",
      "npm:material-ui@0.15.4/utils/autoprefixer.js",
      "npm:inline-style-prefixer@2.0.3.js",
      "npm:inline-style-prefixer@2.0.3/lib/Prefixer.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/flexboxOld.js",
      "npm:inline-style-prefixer@2.0.3/lib/utils/getPrefixedValue.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/flexboxIE.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/transition.js",
      "npm:inline-style-prefixer@2.0.3/lib/utils/unprefixProperty.js",
      "npm:hyphenate-style-name@1.0.1.js",
      "npm:hyphenate-style-name@1.0.1/index.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/gradient.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/sizing.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/flex.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/grabCursor.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/zoomCursor.js",
      "npm:inline-style-prefixer@2.0.3/lib/plugins/calc.js",
      "npm:inline-style-prefixer@2.0.3/lib/prefixProps.js",
      "npm:inline-style-prefixer@2.0.3/lib/utils/capitalizeString.js",
      "npm:inline-style-prefixer@2.0.3/lib/utils/getPrefixedKeyframes.js",
      "npm:inline-style-prefixer@2.0.3/lib/utils/getBrowserInformation.js",
      "npm:bowser@1.4.5.js",
      "npm:bowser@1.4.5/src/bowser.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/prefixAll.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/plugins/flexboxOld.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/plugins/flexboxIE.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/plugins/transition.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/prefixProps.js",
      "npm:inline-style-prefixer@2.0.3/lib/utils/isPrefixedValue.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/plugins/gradient.js",
      "npm:inline-style-prefixer@2.0.3/lib/utils/joinPrefixedValue.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/plugins/sizing.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/plugins/flex.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/plugins/cursor.js",
      "npm:inline-style-prefixer@2.0.3/lib/static/plugins/calc.js",
      "npm:material-ui@0.15.4/styles/baseThemes/lightBaseTheme.js",
      "npm:material-ui@0.15.4/styles/spacing.js",
      "npm:material-ui@0.15.4/utils/colorManipulator.js",
      "npm:lodash@4.15.0/merge.js",
      "npm:lodash@4.15.0/_createAssigner.js",
      "npm:lodash@4.15.0/_isIterateeCall.js",
      "npm:lodash@4.15.0/isObject.js",
      "npm:lodash@4.15.0/_isIndex.js",
      "npm:lodash@4.15.0/isArrayLike.js",
      "npm:lodash@4.15.0/isLength.js",
      "npm:lodash@4.15.0/isFunction.js",
      "npm:lodash@4.15.0/eq.js",
      "npm:lodash@4.15.0/_baseRest.js",
      "npm:lodash@4.15.0/_apply.js",
      "npm:lodash@4.15.0/_baseMerge.js",
      "npm:lodash@4.15.0/isTypedArray.js",
      "npm:lodash@4.15.0/_nodeUtil.js",
      "npm:lodash@4.15.0/_freeGlobal.js",
      "npm:lodash@4.15.0/_baseUnary.js",
      "npm:lodash@4.15.0/_baseIsTypedArray.js",
      "npm:lodash@4.15.0/isObjectLike.js",
      "npm:lodash@4.15.0/isArray.js",
      "npm:lodash@4.15.0/_baseMergeDeep.js",
      "npm:lodash@4.15.0/toPlainObject.js",
      "npm:lodash@4.15.0/keysIn.js",
      "npm:lodash@4.15.0/_baseKeysIn.js",
      "npm:lodash@4.15.0/_nativeKeysIn.js",
      "npm:lodash@4.15.0/_isPrototype.js",
      "npm:lodash@4.15.0/_arrayLikeKeys.js",
      "npm:lodash@4.15.0/isArguments.js",
      "npm:lodash@4.15.0/isArrayLikeObject.js",
      "npm:lodash@4.15.0/_baseTimes.js",
      "npm:lodash@4.15.0/_copyObject.js",
      "npm:lodash@4.15.0/_assignValue.js",
      "npm:lodash@4.15.0/isPlainObject.js",
      "npm:lodash@4.15.0/_isHostObject.js",
      "npm:lodash@4.15.0/_getPrototype.js",
      "npm:lodash@4.15.0/_overArg.js",
      "npm:lodash@4.15.0/_copyArray.js",
      "npm:lodash@4.15.0/_baseClone.js",
      "npm:lodash@4.15.0/keys.js",
      "npm:lodash@4.15.0/_baseKeys.js",
      "npm:lodash@4.15.0/_nativeKeys.js",
      "npm:lodash@4.15.0/isBuffer.js",
      "npm:lodash@4.15.0/stubFalse.js",
      "npm:lodash@4.15.0/_root.js",
      "npm:lodash@4.15.0/_initCloneObject.js",
      "npm:lodash@4.15.0/_baseCreate.js",
      "npm:lodash@4.15.0/_initCloneByTag.js",
      "npm:lodash@4.15.0/_cloneTypedArray.js",
      "npm:lodash@4.15.0/_cloneArrayBuffer.js",
      "npm:lodash@4.15.0/_Uint8Array.js",
      "npm:lodash@4.15.0/_cloneSymbol.js",
      "npm:lodash@4.15.0/_Symbol.js",
      "npm:lodash@4.15.0/_cloneSet.js",
      "npm:lodash@4.15.0/_setToArray.js",
      "npm:lodash@4.15.0/_arrayReduce.js",
      "npm:lodash@4.15.0/_addSetEntry.js",
      "npm:lodash@4.15.0/_cloneRegExp.js",
      "npm:lodash@4.15.0/_cloneMap.js",
      "npm:lodash@4.15.0/_mapToArray.js",
      "npm:lodash@4.15.0/_addMapEntry.js",
      "npm:lodash@4.15.0/_cloneDataView.js",
      "npm:lodash@4.15.0/_initCloneArray.js",
      "npm:lodash@4.15.0/_getTag.js",
      "npm:lodash@4.15.0/_toSource.js",
      "npm:lodash@4.15.0/_baseGetTag.js",
      "npm:lodash@4.15.0/_WeakMap.js",
      "npm:lodash@4.15.0/_getNative.js",
      "npm:lodash@4.15.0/_getValue.js",
      "npm:lodash@4.15.0/_baseIsNative.js",
      "npm:lodash@4.15.0/_isMasked.js",
      "npm:lodash@4.15.0/_coreJsData.js",
      "npm:lodash@4.15.0/_Set.js",
      "npm:lodash@4.15.0/_Promise.js",
      "npm:lodash@4.15.0/_Map.js",
      "npm:lodash@4.15.0/_DataView.js",
      "npm:lodash@4.15.0/_getAllKeys.js",
      "npm:lodash@4.15.0/_getSymbols.js",
      "npm:lodash@4.15.0/stubArray.js",
      "npm:lodash@4.15.0/_baseGetAllKeys.js",
      "npm:lodash@4.15.0/_arrayPush.js",
      "npm:lodash@4.15.0/_copySymbols.js",
      "npm:lodash@4.15.0/_cloneBuffer.js",
      "npm:lodash@4.15.0/_baseAssign.js",
      "npm:lodash@4.15.0/_arrayEach.js",
      "npm:lodash@4.15.0/_Stack.js",
      "npm:lodash@4.15.0/_stackSet.js",
      "npm:lodash@4.15.0/_MapCache.js",
      "npm:lodash@4.15.0/_mapCacheSet.js",
      "npm:lodash@4.15.0/_getMapData.js",
      "npm:lodash@4.15.0/_isKeyable.js",
      "npm:lodash@4.15.0/_mapCacheHas.js",
      "npm:lodash@4.15.0/_mapCacheGet.js",
      "npm:lodash@4.15.0/_mapCacheDelete.js",
      "npm:lodash@4.15.0/_mapCacheClear.js",
      "npm:lodash@4.15.0/_ListCache.js",
      "npm:lodash@4.15.0/_listCacheSet.js",
      "npm:lodash@4.15.0/_assocIndexOf.js",
      "npm:lodash@4.15.0/_listCacheHas.js",
      "npm:lodash@4.15.0/_listCacheGet.js",
      "npm:lodash@4.15.0/_listCacheDelete.js",
      "npm:lodash@4.15.0/_listCacheClear.js",
      "npm:lodash@4.15.0/_Hash.js",
      "npm:lodash@4.15.0/_hashSet.js",
      "npm:lodash@4.15.0/_nativeCreate.js",
      "npm:lodash@4.15.0/_hashHas.js",
      "npm:lodash@4.15.0/_hashGet.js",
      "npm:lodash@4.15.0/_hashDelete.js",
      "npm:lodash@4.15.0/_hashClear.js",
      "npm:lodash@4.15.0/_stackHas.js",
      "npm:lodash@4.15.0/_stackGet.js",
      "npm:lodash@4.15.0/_stackDelete.js",
      "npm:lodash@4.15.0/_stackClear.js",
      "npm:lodash@4.15.0/_assignMergeValue.js",
      "npm:material-ui@0.15.4/styles/baseThemes/darkBaseTheme.js",
      "npm:material-ui@0.15.4/styles/MuiThemeProvider.js",
      "npm:react@15.3.1.js",
      "npm:react@15.3.1/react.js",
      "npm:react@15.3.1/lib/React.js",
      "npm:react@15.3.1/lib/ReactElementValidator.js",
      "npm:react@15.3.1/lib/onlyChild.js",
      "npm:react@15.3.1/lib/ReactDOMFactories.js",
      "npm:react@15.3.1/lib/ReactPureComponent.js",
      "npm:material-ui@0.15.4.js",
      "npm:material-ui@0.15.4/index.js",
      "npm:material-ui@0.15.4/Toolbar/ToolbarTitle.js",
      "npm:simple-assign@0.1.0.js",
      "npm:simple-assign@0.1.0/index.js",
      "npm:material-ui@0.15.4/Toolbar/ToolbarSeparator.js",
      "npm:material-ui@0.15.4/Toolbar/ToolbarGroup.js",
      "npm:material-ui@0.15.4/Toolbar/index.js",
      "npm:material-ui@0.15.4/Toolbar/Toolbar.js",
      "npm:material-ui@0.15.4/Toggle/index.js",
      "npm:material-ui@0.15.4/Toggle/Toggle.js",
      "npm:material-ui@0.15.4/internal/EnhancedSwitch.js",
      "npm:material-ui@0.15.4/Paper/index.js",
      "npm:material-ui@0.15.4/Paper/Paper.js",
      "npm:material-ui@0.15.4/utils/propTypes.js",
      "npm:material-ui@0.15.4/internal/TouchRipple.js",
      "npm:material-ui@0.15.4/internal/CircleRipple.js",
      "npm:material-ui@0.15.4/utils/autoPrefix.js",
      "npm:recompose@0.20.2/shallowEqual.js",
      "npm:material-ui@0.15.4/utils/dom.js",
      "npm:react-addons-transition-group@15.3.1.js",
      "npm:react-addons-transition-group@15.3.1/index.js",
      "npm:react@15.3.1/lib/ReactTransitionGroup.js",
      "npm:react@15.3.1/lib/ReactTransitionChildMapping.js",
      "npm:material-ui@0.15.4/internal/FocusRipple.js",
      "npm:material-ui@0.15.4/internal/ScaleIn.js",
      "npm:material-ui@0.15.4/internal/ScaleInChild.js",
      "npm:keycode@2.1.6.js",
      "npm:keycode@2.1.6/index.js",
      "npm:react-event-listener@0.2.1.js",
      "npm:react-event-listener@0.2.1/lib/index.js",
      "npm:material-ui@0.15.4/TimePicker/index.js",
      "npm:material-ui@0.15.4/TimePicker/TimePicker.js",
      "npm:material-ui@0.15.4/TimePicker/timeUtils.js",
      "npm:material-ui@0.15.4/TextField/index.js",
      "npm:material-ui@0.15.4/TextField/TextField.js",
      "npm:material-ui@0.15.4/TextField/TextFieldUnderline.js",
      "npm:material-ui@0.15.4/TextField/TextFieldLabel.js",
      "npm:material-ui@0.15.4/TextField/TextFieldHint.js",
      "npm:material-ui@0.15.4/TextField/EnhancedTextarea.js",
      "npm:material-ui@0.15.4/utils/deprecatedPropType.js",
      "npm:material-ui@0.15.4/TimePicker/TimePickerDialog.js",
      "npm:material-ui@0.15.4/FlatButton/index.js",
      "npm:material-ui@0.15.4/FlatButton/FlatButton.js",
      "npm:material-ui@0.15.4/FlatButton/FlatButtonLabel.js",
      "npm:material-ui@0.15.4/internal/EnhancedButton.js",
      "npm:material-ui@0.15.4/utils/events.js",
      "npm:material-ui@0.15.4/utils/childUtils.js",
      "npm:react-addons-create-fragment@15.3.1.js",
      "npm:react-addons-create-fragment@15.3.1/index.js",
      "npm:react@15.3.1/lib/ReactFragment.js",
      "npm:material-ui@0.15.4/Dialog/index.js",
      "npm:material-ui@0.15.4/Dialog/Dialog.js",
      "npm:material-ui@0.15.4/internal/RenderToLayer.js",
      "npm:material-ui@0.15.4/internal/Overlay.js",
      "npm:material-ui@0.15.4/internal/AutoLockScrolling.js",
      "npm:material-ui@0.15.4/TimePicker/Clock.js",
      "npm:material-ui@0.15.4/TimePicker/ClockMinutes.js",
      "npm:material-ui@0.15.4/TimePicker/ClockPointer.js",
      "npm:material-ui@0.15.4/TimePicker/ClockNumber.js",
      "npm:material-ui@0.15.4/TimePicker/ClockHours.js",
      "npm:material-ui@0.15.4/TimePicker/TimeDisplay.js",
      "npm:material-ui@0.15.4/Table/TableRowColumn.js",
      "npm:material-ui@0.15.4/Table/TableRow.js",
      "npm:material-ui@0.15.4/Table/TableHeaderColumn.js",
      "npm:material-ui@0.15.4/internal/Tooltip.js",
      "npm:material-ui@0.15.4/Table/TableHeader.js",
      "npm:material-ui@0.15.4/Checkbox/index.js",
      "npm:material-ui@0.15.4/Checkbox/Checkbox.js",
      "npm:material-ui@0.15.4/svg-icons/toggle/check-box.js",
      "npm:material-ui@0.15.4/SvgIcon/index.js",
      "npm:material-ui@0.15.4/SvgIcon/SvgIcon.js",
      "npm:recompose@0.20.2/pure.js",
      "npm:recompose@0.20.2/createHelper.js",
      "npm:recompose@0.20.2/wrapDisplayName.js",
      "npm:recompose@0.20.2/getDisplayName.js",
      "npm:recompose@0.20.2/shouldUpdate.js",
      "npm:recompose@0.20.2/createEagerFactory.js",
      "npm:recompose@0.20.2/isReferentiallyTransparentFunctionComponent.js",
      "npm:recompose@0.20.2/isClassComponent.js",
      "npm:recompose@0.20.2/utils/createEagerElementUtil.js",
      "npm:material-ui@0.15.4/svg-icons/toggle/check-box-outline-blank.js",
      "npm:material-ui@0.15.4/Table/TableFooter.js",
      "npm:material-ui@0.15.4/Table/TableBody.js",
      "npm:material-ui@0.15.4/internal/ClickAwayListener.js",
      "npm:material-ui@0.15.4/Table/index.js",
      "npm:material-ui@0.15.4/Table/Table.js",
      "npm:material-ui@0.15.4/Tabs/Tab.js",
      "npm:material-ui@0.15.4/Tabs/index.js",
      "npm:material-ui@0.15.4/Tabs/Tabs.js",
      "npm:material-ui@0.15.4/Tabs/InkBar.js",
      "npm:material-ui@0.15.4/Tabs/TabTemplate.js",
      "npm:material-ui@0.15.4/Snackbar/index.js",
      "npm:material-ui@0.15.4/Snackbar/Snackbar.js",
      "npm:material-ui@0.15.4/Snackbar/SnackbarBody.js",
      "npm:material-ui@0.15.4/utils/withWidth.js",
      "npm:material-ui@0.15.4/Stepper/Stepper.js",
      "npm:material-ui@0.15.4/Stepper/StepConnector.js",
      "npm:material-ui@0.15.4/Stepper/StepLabel.js",
      "npm:material-ui@0.15.4/svg-icons/action/check-circle.js",
      "npm:material-ui@0.15.4/Stepper/StepContent.js",
      "npm:material-ui@0.15.4/internal/ExpandTransition.js",
      "npm:material-ui@0.15.4/internal/ExpandTransitionChild.js",
      "npm:material-ui@0.15.4/Stepper/StepButton.js",
      "npm:material-ui@0.15.4/Stepper/Step.js",
      "npm:material-ui@0.15.4/Subheader/index.js",
      "npm:material-ui@0.15.4/Subheader/Subheader.js",
      "npm:material-ui@0.15.4/Slider/index.js",
      "npm:material-ui@0.15.4/Slider/Slider.js",
      "npm:material-ui@0.15.4/SelectField/index.js",
      "npm:material-ui@0.15.4/SelectField/SelectField.js",
      "npm:material-ui@0.15.4/DropDownMenu/index.js",
      "npm:material-ui@0.15.4/MenuItem/MenuItem.js",
      "npm:material-ui@0.15.4/Menu/Menu.js",
      "npm:material-ui@0.15.4/Menu/menuUtils.js",
      "npm:material-ui@0.15.4/List/List.js",
      "npm:material-ui@0.15.4/List/ListItem.js",
      "npm:material-ui@0.15.4/List/NestedList.js",
      "npm:material-ui@0.15.4/svg-icons/navigation/expand-more.js",
      "npm:material-ui@0.15.4/svg-icons/navigation/expand-less.js",
      "npm:material-ui@0.15.4/IconButton/index.js",
      "npm:material-ui@0.15.4/IconButton/IconButton.js",
      "npm:material-ui@0.15.4/FontIcon/index.js",
      "npm:material-ui@0.15.4/FontIcon/FontIcon.js",
      "npm:material-ui@0.15.4/svg-icons/navigation/check.js",
      "npm:material-ui@0.15.4/Popover/Popover.js",
      "npm:material-ui@0.15.4/Popover/PopoverAnimationDefault.js",
      "npm:lodash@4.15.0/throttle.js",
      "npm:lodash@4.15.0/debounce.js",
      "npm:lodash@4.15.0/toNumber.js",
      "npm:lodash@4.15.0/isSymbol.js",
      "npm:lodash@4.15.0/now.js",
      "npm:material-ui@0.15.4/DropDownMenu/DropDownMenu.js",
      "npm:material-ui@0.15.4/Popover/PopoverAnimationVertical.js",
      "npm:material-ui@0.15.4/internal/ClearFix.js",
      "npm:material-ui@0.15.4/internal/BeforeAfterWrapper.js",
      "npm:material-ui@0.15.4/svg-icons/navigation/arrow-drop-down.js",
      "npm:material-ui@0.15.4/RefreshIndicator/index.js",
      "npm:material-ui@0.15.4/RefreshIndicator/RefreshIndicator.js",
      "npm:material-ui@0.15.4/RaisedButton/index.js",
      "npm:material-ui@0.15.4/RaisedButton/RaisedButton.js",
      "npm:material-ui@0.15.4/RadioButton/RadioButtonGroup.js",
      "npm:material-ui@0.15.4/RadioButton/index.js",
      "npm:material-ui@0.15.4/RadioButton/RadioButton.js",
      "npm:material-ui@0.15.4/svg-icons/toggle/radio-button-checked.js",
      "npm:material-ui@0.15.4/svg-icons/toggle/radio-button-unchecked.js",
      "npm:material-ui@0.15.4/Popover/index.js",
      "npm:material-ui@0.15.4/MenuItem/index.js",
      "npm:material-ui@0.15.4/Menu/index.js",
      "npm:material-ui@0.15.4/List/MakeSelectable.js",
      "npm:material-ui@0.15.4/List/index.js",
      "npm:material-ui@0.15.4/LinearProgress/index.js",
      "npm:material-ui@0.15.4/LinearProgress/LinearProgress.js",
      "npm:material-ui@0.15.4/IconMenu/index.js",
      "npm:material-ui@0.15.4/IconMenu/IconMenu.js",
      "npm:material-ui@0.15.4/GridList/GridTile.js",
      "npm:material-ui@0.15.4/GridList/index.js",
      "npm:material-ui@0.15.4/GridList/GridList.js",
      "npm:material-ui@0.15.4/FloatingActionButton/index.js",
      "npm:material-ui@0.15.4/FloatingActionButton/FloatingActionButton.js",
      "npm:material-ui@0.15.4/Drawer/index.js",
      "npm:material-ui@0.15.4/Drawer/Drawer.js",
      "npm:material-ui@0.15.4/Divider/index.js",
      "npm:material-ui@0.15.4/Divider/Divider.js",
      "npm:material-ui@0.15.4/DatePicker/index.js",
      "npm:material-ui@0.15.4/DatePicker/DatePicker.js",
      "npm:material-ui@0.15.4/DatePicker/DatePickerDialog.js",
      "npm:material-ui@0.15.4/DatePicker/dateUtils.js",
      "npm:material-ui@0.15.4/DatePicker/Calendar.js",
      "npm:material-ui@0.15.4/internal/SlideIn.js",
      "npm:material-ui@0.15.4/internal/SlideInChild.js",
      "npm:material-ui@0.15.4/DatePicker/DateDisplay.js",
      "npm:material-ui@0.15.4/DatePicker/CalendarToolbar.js",
      "npm:material-ui@0.15.4/svg-icons/navigation/chevron-right.js",
      "npm:material-ui@0.15.4/svg-icons/navigation/chevron-left.js",
      "npm:material-ui@0.15.4/DatePicker/CalendarYear.js",
      "npm:material-ui@0.15.4/DatePicker/YearButton.js",
      "npm:material-ui@0.15.4/DatePicker/CalendarMonth.js",
      "npm:material-ui@0.15.4/DatePicker/DayButton.js",
      "npm:material-ui@0.15.4/DatePicker/CalendarActionButtons.js",
      "npm:material-ui@0.15.4/CircularProgress/index.js",
      "npm:material-ui@0.15.4/CircularProgress/CircularProgress.js",
      "npm:material-ui@0.15.4/Chip/index.js",
      "npm:material-ui@0.15.4/Chip/Chip.js",
      "npm:material-ui@0.15.4/svg-icons/navigation/cancel.js",
      "npm:material-ui@0.15.4/Card/CardText.js",
      "npm:material-ui@0.15.4/Card/CardTitle.js",
      "npm:material-ui@0.15.4/Card/CardMedia.js",
      "npm:material-ui@0.15.4/Card/CardHeader.js",
      "npm:material-ui@0.15.4/Avatar/index.js",
      "npm:material-ui@0.15.4/Avatar/Avatar.js",
      "npm:material-ui@0.15.4/Card/CardActions.js",
      "npm:material-ui@0.15.4/Card/index.js",
      "npm:material-ui@0.15.4/Card/CardExpandable.js",
      "npm:material-ui@0.15.4/svg-icons/hardware/keyboard-arrow-down.js",
      "npm:material-ui@0.15.4/svg-icons/hardware/keyboard-arrow-up.js",
      "npm:material-ui@0.15.4/Card/Card.js",
      "npm:material-ui@0.15.4/Badge/index.js",
      "npm:material-ui@0.15.4/Badge/Badge.js",
      "npm:material-ui@0.15.4/AutoComplete/index.js",
      "npm:material-ui@0.15.4/AutoComplete/AutoComplete.js",
      "npm:material-ui@0.15.4/AppBar/index.js",
      "npm:material-ui@0.15.4/AppBar/AppBar.js",
      "npm:material-ui@0.15.4/svg-icons/navigation/menu.js",
      "npm:react-router@2.7.0.js",
      "npm:react-router@2.7.0/lib/index.js",
      "npm:react-router@2.7.0/lib/createMemoryHistory.js",
      "npm:history@2.1.2/lib/createMemoryHistory.js",
      "npm:history@2.1.2/lib/createHistory.js",
      "npm:history@2.1.2/lib/deprecate.js",
      "npm:warning@2.1.0.js",
      "npm:warning@2.1.0/browser.js",
      "npm:history@2.1.2/lib/runTransitionHook.js",
      "npm:history@2.1.2/lib/createLocation.js",
      "npm:history@2.1.2/lib/PathUtils.js",
      "npm:history@2.1.2/lib/Actions.js",
      "npm:history@2.1.2/lib/AsyncUtils.js",
      "npm:deep-equal@1.0.1.js",
      "npm:deep-equal@1.0.1/index.js",
      "npm:deep-equal@1.0.1/lib/is_arguments.js",
      "npm:deep-equal@1.0.1/lib/keys.js",
      "npm:invariant@2.2.1.js",
      "npm:invariant@2.2.1/browser.js",
      "npm:history@2.1.2/lib/useBasename.js",
      "npm:history@2.1.2/lib/ExecutionEnvironment.js",
      "npm:history@2.1.2/lib/useQueries.js",
      "npm:query-string@3.0.3.js",
      "npm:query-string@3.0.3/index.js",
      "npm:strict-uri-encode@1.1.0.js",
      "npm:strict-uri-encode@1.1.0/index.js",
      "npm:react-router@2.7.0/lib/hashHistory.js",
      "npm:react-router@2.7.0/lib/createRouterHistory.js",
      "npm:react-router@2.7.0/lib/useRouterHistory.js",
      "npm:history@2.1.2/lib/createHashHistory.js",
      "npm:history@2.1.2/lib/createDOMHistory.js",
      "npm:history@2.1.2/lib/DOMUtils.js",
      "npm:history@2.1.2/lib/DOMStateStorage.js",
      "npm:react-router@2.7.0/lib/browserHistory.js",
      "npm:history@2.1.2/lib/createBrowserHistory.js",
      "npm:react-router@2.7.0/lib/applyRouterMiddleware.js",
      "npm:react-router@2.7.0/lib/routerWarning.js",
      "npm:react-router@2.7.0/lib/RouterContext.js",
      "npm:react-router@2.7.0/lib/RouteUtils.js",
      "npm:react-router@2.7.0/lib/getRouteParams.js",
      "npm:react-router@2.7.0/lib/PatternUtils.js",
      "npm:react-router@2.7.0/lib/deprecateObjectProperties.js",
      "npm:react-router@2.7.0/lib/match.js",
      "npm:react-router@2.7.0/lib/RouterUtils.js",
      "npm:react-router@2.7.0/lib/createTransitionManager.js",
      "npm:react-router@2.7.0/lib/matchRoutes.js",
      "npm:react-router@2.7.0/lib/makeStateWithLocation.js",
      "npm:react-router@2.7.0/lib/AsyncUtils.js",
      "npm:react-router@2.7.0/lib/getComponents.js",
      "npm:react-router@2.7.0/lib/isActive.js",
      "npm:react-router@2.7.0/lib/TransitionUtils.js",
      "npm:react-router@2.7.0/lib/computeChangedRoutes.js",
      "npm:react-router@2.7.0/lib/RoutingContext.js",
      "npm:react-router@2.7.0/lib/useRoutes.js",
      "npm:react-router@2.7.0/lib/RouteContext.js",
      "npm:react-router@2.7.0/lib/Lifecycle.js",
      "npm:react-router@2.7.0/lib/History.js",
      "npm:react-router@2.7.0/lib/InternalPropTypes.js",
      "npm:react-router@2.7.0/lib/Route.js",
      "npm:react-router@2.7.0/lib/Redirect.js",
      "npm:react-router@2.7.0/lib/IndexRoute.js",
      "npm:react-router@2.7.0/lib/IndexRedirect.js",
      "npm:react-router@2.7.0/lib/withRouter.js",
      "npm:react-router@2.7.0/lib/PropTypes.js",
      "npm:hoist-non-react-statics@1.2.0.js",
      "npm:hoist-non-react-statics@1.2.0/index.js",
      "npm:react-router@2.7.0/lib/IndexLink.js",
      "npm:react-router@2.7.0/lib/Link.js",
      "npm:react-router@2.7.0/lib/Router.js",
      "npm:mobx-react@3.5.5.js",
      "npm:mobx-react@3.5.5/index.js",
      "npm:mobx@2.5.1.js",
      "npm:mobx@2.5.1/lib/mobx.js",
      "npm:babel-runtime@5.8.38/helpers/class-call-check.js",
      "npm:babel-runtime@5.8.38/helpers/create-class.js",
      "npm:babel-runtime@5.8.38/core-js/object/define-property.js",
      "npm:core-js@1.2.7/library/fn/object/define-property.js",
      "npm:core-js@1.2.7/library/modules/$.js",
      "npm:babel-runtime@5.8.38/helpers/inherits.js",
      "npm:babel-runtime@5.8.38/core-js/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/$.core.js",
      "npm:core-js@1.2.7/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/$.set-proto.js",
      "npm:core-js@1.2.7/library/modules/$.ctx.js",
      "npm:core-js@1.2.7/library/modules/$.a-function.js",
      "npm:core-js@1.2.7/library/modules/$.an-object.js",
      "npm:core-js@1.2.7/library/modules/$.is-object.js",
      "npm:core-js@1.2.7/library/modules/$.export.js",
      "npm:core-js@1.2.7/library/modules/$.global.js",
      "npm:babel-runtime@5.8.38/core-js/object/create.js",
      "npm:core-js@1.2.7/library/fn/object/create.js",
      "npm:babel-runtime@5.8.38/helpers/get.js",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/$.object-sap.js",
      "npm:core-js@1.2.7/library/modules/$.fails.js",
      "npm:core-js@1.2.7/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/library/modules/$.defined.js",
      "npm:core-js@1.2.7/library/modules/$.iobject.js",
      "npm:core-js@1.2.7/library/modules/$.cof.js",
      "components/Page.js",
      "components/Home.js"
    ]
  },

  map: {
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "capaj/systemjs-hot-reloader": "github:capaj/systemjs-hot-reloader@0.6.0",
    "core-js": "npm:core-js@1.2.7",
    "material-ui": "npm:material-ui@0.15.4",
    "mobx": "npm:mobx@2.5.1",
    "mobx-react": "npm:mobx-react@3.5.5",
    "react": "npm:react@15.3.1",
    "react-dom": "npm:react-dom@15.3.1",
    "react-markdown": "npm:react-markdown@2.4.2",
    "react-router": "npm:react-router@2.7.0",
    "react-tap-event-plugin": "npm:react-tap-event-plugin@1.0.0",
    "github:capaj/systemjs-hot-reloader@0.6.0": {
      "debug": "npm:debug@2.2.0",
      "socket.io-client": "github:socketio/socket.io-client@1.4.8",
      "weakee": "npm:weakee@1.0.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-domain@0.1.0": {
      "domain-browser": "npm:domain-browser@1.1.7"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.9"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:jspm/nodelibs-zlib@0.1.0": {
      "browserify-zlib": "npm:browserify-zlib@0.1.4"
    },
    "npm:asap@2.0.4": {
      "domain": "github:jspm/nodelibs-domain@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:browserify-zlib@0.1.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "pako": "npm:pako@0.2.9",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@2.1.5",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:buffer-shims@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:commonmark-react-renderer@4.3.1": {
      "commonmark": "npm:commonmark@0.24.0",
      "in-publish": "npm:in-publish@2.0.0",
      "lodash.assign": "npm:lodash.assign@4.2.0",
      "lodash.isplainobject": "npm:lodash.isplainobject@4.0.6",
      "pascalcase": "npm:pascalcase@0.1.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.1",
      "xss-filters": "npm:xss-filters@1.2.7"
    },
    "npm:commonmark@0.24.0": {
      "entities": "npm:entities@1.1.1",
      "mdurl": "npm:mdurl@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "string.prototype.repeat": "npm:string.prototype.repeat@0.2.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:debug@2.2.0": {
      "ms": "npm:ms@0.7.1"
    },
    "npm:domain-browser@1.1.7": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:encoding@0.1.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "iconv-lite": "npm:iconv-lite@0.4.13"
    },
    "npm:entities@1.1.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:fbjs@0.2.1": {
      "core-js": "npm:core-js@1.2.7",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "promise": "npm:promise@7.1.1",
      "whatwg-fetch": "npm:whatwg-fetch@0.9.0"
    },
    "npm:fbjs@0.8.4": {
      "core-js": "npm:core-js@1.2.7",
      "immutable": "npm:immutable@3.8.1",
      "isomorphic-fetch": "npm:isomorphic-fetch@2.2.1",
      "loose-envify": "npm:loose-envify@1.2.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "promise": "npm:promise@7.1.1",
      "ua-parser-js": "npm:ua-parser-js@0.7.10"
    },
    "npm:history@2.1.2": {
      "deep-equal": "npm:deep-equal@1.0.1",
      "invariant": "npm:invariant@2.2.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "query-string": "npm:query-string@3.0.3",
      "warning": "npm:warning@2.1.0"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:iconv-lite@0.4.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:in-publish@2.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:inline-style-prefixer@2.0.3": {
      "bowser": "npm:bowser@1.4.5",
      "hyphenate-style-name": "npm:hyphenate-style-name@1.0.1"
    },
    "npm:invariant@2.2.1": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:isomorphic-fetch@2.2.1": {
      "node-fetch": "npm:node-fetch@1.6.1",
      "whatwg-fetch": "npm:whatwg-fetch@0.9.0"
    },
    "npm:loose-envify@1.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "js-tokens": "npm:js-tokens@1.0.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:material-ui@0.15.4": {
      "inline-style-prefixer": "npm:inline-style-prefixer@2.0.3",
      "keycode": "npm:keycode@2.1.6",
      "lodash": "npm:lodash@4.15.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.1",
      "react-addons-create-fragment": "npm:react-addons-create-fragment@15.3.1",
      "react-addons-transition-group": "npm:react-addons-transition-group@15.3.1",
      "react-dom": "npm:react-dom@15.3.1",
      "react-event-listener": "npm:react-event-listener@0.2.1",
      "react-tap-event-plugin": "npm:react-tap-event-plugin@1.0.0",
      "recompose": "npm:recompose@0.20.2",
      "simple-assign": "npm:simple-assign@0.1.0",
      "warning": "npm:warning@3.0.0"
    },
    "npm:mobx-react@3.5.5": {
      "hoist-non-react-statics": "npm:hoist-non-react-statics@1.2.0",
      "mobx": "npm:mobx@2.5.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:node-fetch@1.6.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "encoding": "npm:encoding@0.1.12",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "is-stream": "npm:is-stream@1.1.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    },
    "npm:pako@0.2.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process-nextick-args@1.0.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.9": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:promise@7.1.1": {
      "asap": "npm:asap@2.0.4",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:query-string@3.0.3": {
      "strict-uri-encode": "npm:strict-uri-encode@1.1.0"
    },
    "npm:react-addons-create-fragment@15.3.1": {
      "react": "npm:react@15.3.1"
    },
    "npm:react-addons-transition-group@15.3.1": {
      "react": "npm:react@15.3.1"
    },
    "npm:react-dom@15.3.1": {
      "react": "npm:react@15.3.1"
    },
    "npm:react-event-listener@0.2.1": {
      "fbjs": "npm:fbjs@0.8.4"
    },
    "npm:react-markdown@2.4.2": {
      "commonmark": "npm:commonmark@0.24.0",
      "commonmark-react-renderer": "npm:commonmark-react-renderer@4.3.1",
      "in-publish": "npm:in-publish@2.0.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.1"
    },
    "npm:react-router@2.7.0": {
      "history": "npm:history@2.1.2",
      "hoist-non-react-statics": "npm:hoist-non-react-statics@1.2.0",
      "invariant": "npm:invariant@2.2.1",
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.1",
      "warning": "npm:warning@3.0.0"
    },
    "npm:react-tap-event-plugin@1.0.0": {
      "fbjs": "npm:fbjs@0.2.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.1"
    },
    "npm:react@15.3.1": {
      "fbjs": "npm:fbjs@0.8.4",
      "loose-envify": "npm:loose-envify@1.2.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:readable-stream@2.1.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-shims": "npm:buffer-shims@1.0.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "process-nextick-args": "npm:process-nextick-args@1.0.7",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util-deprecate": "npm:util-deprecate@1.0.2"
    },
    "npm:recompose@0.20.2": {
      "change-emitter": "npm:change-emitter@0.1.2",
      "fbjs": "npm:fbjs@0.8.4",
      "hoist-non-react-statics": "npm:hoist-non-react-statics@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.1",
      "symbol-observable": "npm:symbol-observable@0.2.4"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:ua-parser-js@0.7.10": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util-deprecate@1.0.2": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:warning@2.1.0": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:warning@3.0.0": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:xss-filters@1.2.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
